"""empty message

Revision ID: 45395b974e2d
Revises: c39675006f1c
Create Date: 2016-07-05 11:52:04.466489

"""

# revision identifiers, used by Alembic.
revision = '45395b974e2d'
down_revision = 'c39675006f1c'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('dialog_id', sa.String(length=250), nullable=True))
    op.create_unique_constraint(None, 'users', ['dialog_id'])
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='unique')
    op.drop_column('users', 'dialog_id')
    ### end Alembic commands ###
