"""empty message

Revision ID: 63abb0f81ad8
Revises: 809c99d4ad12
Create Date: 2016-06-02 20:05:08.926578

"""

# revision identifiers, used by Alembic.
revision = '63abb0f81ad8'
down_revision = '809c99d4ad12'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('timestamp', sa.DateTime(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'timestamp')
    ### end Alembic commands ###
