"""empty message

Revision ID: 809c99d4ad12
Revises: 0335e6349e41
Create Date: 2016-06-02 19:04:41.003825

"""

# revision identifiers, used by Alembic.
revision = '809c99d4ad12'
down_revision = '0335e6349e41'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=80), nullable=True),
    sa.Column('email', sa.String(length=120), nullable=True),
    sa.Column('phone_number', sa.String(length=120), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('phone_number'),
    sa.UniqueConstraint('username')
    )
    op.add_column(u'messages', sa.Column('user_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'messages', 'users', ['user_id'], ['id'])
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'messages', type_='foreignkey')
    op.drop_column(u'messages', 'user_id')
    op.drop_table('users')
    ### end Alembic commands ###
