"""empty message

Revision ID: c39675006f1c
Revises: 923bf9dd26a6
Create Date: 2016-07-05 10:40:58.070228

"""

# revision identifiers, used by Alembic.
revision = 'c39675006f1c'
down_revision = '923bf9dd26a6'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('responses',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('response', sa.String(), nullable=True),
    sa.Column('dialogid', sa.String(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('message_id', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['message_id'], ['messages.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_column(u'messages', 'response')
    op.add_column(u'users', sa.Column('facebook_id', sa.String(length=250), nullable=True))
    op.add_column(u'users', sa.Column('firstname', sa.String(length=80), nullable=True))
    op.add_column(u'users', sa.Column('lastname', sa.String(length=120), nullable=True))
    op.create_unique_constraint(None, 'users', ['facebook_id'])
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='unique')
    op.drop_column(u'users', 'lastname')
    op.drop_column(u'users', 'firstname')
    op.drop_column(u'users', 'facebook_id')
    op.add_column(u'messages', sa.Column('response', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_table('responses')
    ### end Alembic commands ###
