"""empty message

Revision ID: e75d186ea631
Revises: None
Create Date: 2016-05-30 12:05:54.690910

"""

# revision identifiers, used by Alembic.
revision = 'e75d186ea631'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('messages', sa.Column('response', sa.String(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('messages', 'response')
    ### end Alembic commands ###
